### ISSUE TITLE
About banana_rows.csv

### ISSUE THREAD

**Issue by RorschachChen** [LiangSiyuan21/BadCLIP#2]
Talented work! I am wondering if banana_rows.csv is collected from CC3M which only contains pairs related to "banana", not overlapping with train500k_fixed.csv.Or, if it is convenient for you to share the related csv file? This will facilitate the effort to run your code. Hope you all well.Thanks.

**Comment by LiangSiyuan21** [comment]
Missing files added at data/ImageNet1K/validation/banana_rows.csv
